steps:
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: gsutil
    args: ["cp", "-r", "gs://erik-jevin-melba-step-2020/GeoLite2-City.mmdb", "resources/GeoLite2-City.mmdb"]
  - name: "maven:3-jdk-8"
    entrypoint: mvn
    args: ["package", "test"]
  - name: "maven:3-jdk-8"
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]

